---
# tasks file for jenkins
#install jenkins on ubuntu


- name: execute some shell commands
  ansible.builtin.shell:
    cmd: |
      wget -O /usr/share/keyrings/jenkins-keyring.asc \
      https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
  register: check_jenkins
  when: ansible_facts['distribution'] == 'Ubuntu'


- name: Update repositories cache 
  ansible.builtin.apt:
    update_cache: yes
  when: check_jenkins.changed == true and ansible_facts['distribution'] == 'Ubuntu'

- name: install java
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop:
    - fontconfig
    - openjdk-17-jre
  when: ansible_facts['distribution'] == 'Ubuntu'
  notify: install_jenkins

#------------------------------------------------------------------------------------------------------------------------------

#install jenkins on centos


- name: This command will change the working directory to somedir/
  ansible.builtin.shell:
    cmd: |
      wget -O /etc/yum.repos.d/jenkins.repo \
      https://pkg.jenkins.io/redhat-stable/jenkins.repo
      rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  when: ansible_facts['distribution'] == 'Centos'

- name: update cache
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_facts['distribution'] == 'Centos'

- name: Install java and jenkins
  ansible.builtin.yum:
    name: "{{item}}"
    state: present
  loop:
    - fontconfig
    - java-17-openjdk
    - jenkins
  when: ansible_facts['distribution'] == 'Centos'  
  notify: restart and enable service





